### ISSUE TITLE
mod failed to load

### ISSUE THREAD

**Issue by xX0Shadow0Xx** [Sniffity/Panthalassa#16]
Panthalassa mod cant load i tried reseting mc a few times
here's the log
---- Minecraft Crash Report ----
// Surprise! Haha. Well, this is awkward.

Time: 2022-11-13 15:46:50
Description: Mod loading error has occurred

java.lang.Exception: Mod Loading has failed
	at net.minecraftforge.logging.CrashReportExtender.dumpModLoadingCrashReport(CrashReportExtender.java:55) ~[forge-1.19.2-43.1.1-universal.jar%23209!/:?] {re:classloading}
	at net.minecraftforge.client.loading.ClientModLoader.completeModLoading(ClientModLoader.java:167) ~[forge-1.19.2-43.1.1-universal.jar%23209!/:?] {re:classloading,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.lambda$new$2(Minecraft.java:585) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.Util.m_137521_(Util.java:604) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:classloading,xf:OptiFine:default,re:mixin,xf:OptiFine:default}
	at net.minecraft.client.Minecraft.lambda$new$3(Minecraft.java:579) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.gui.screens.LoadingOverlay.m_6305_(LoadingOverlay.java:196) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:classloading,xf:OptiFine:default}
	at net.minecraft.client.renderer.GameRenderer.m_109093_(GameRenderer.java:1290) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,xf:OptiFine:default,re:classloading,pl:accesstransformer:B,xf:OptiFine:default,pl:mixin:APP:create.mixins.json:GameRendererMixin,pl:mixin:APP:create.mixins.json:accessor.GameRendererAccessor,pl:mixin:A}
	at net.minecraft.client.Minecraft.m_91383_(Minecraft.java:1115) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.Minecraft.m_91374_(Minecraft.java:700) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:mixin,pl:accesstransformer:B,pl:runtimedistcleaner:A,re:classloading,pl:accesstransformer:B,pl:mixin:APP:balm.mixins.json:MinecraftMixin,pl:mixin:APP:flywheel.mixins.json:PausedPartialTickAccessor,pl:mixin:APP:architectury.mixins.json:MixinMinecraft,pl:mixin:APP:create.mixins.json:WindowResizeMixin,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.m_239872_(Main.java:212) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at net.minecraft.client.main.Main.main(Main.java:51) ~[client-1.19.2-20220805.130853-srg.jar%23204!/:?] {re:classloading,re:mixin,pl:runtimedistcleaner:A,pl:mixin:A,pl:runtimedistcleaner:A}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method) ~[?:?] {}
	at jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77) ~[?:?] {}
	at jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43) ~[?:?] {}
	at java.lang.reflect.Method.invoke(Method.java:568) ~[?:?] {}
	at net.minecraftforge.fml.loading.targets.CommonClientLaunchHandler.lambda$launchService$0(CommonClientLaunchHandler.java:27) ~[fmlloader-1.19.2-43.1.1.jar%2395!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandlerDecorator.launch(LaunchServiceHandlerDecorator.java:30) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:53) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.LaunchServiceHandler.launch(LaunchServiceHandler.java:71) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.run(Launcher.java:106) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.Launcher.main(Launcher.java:77) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:26) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.modlauncher.BootstrapLaunchConsumer.accept(BootstrapLaunchConsumer.java:23) [modlauncher-10.0.8.jar%2382!/:?] {}
	at cpw.mods.bootstraplauncher.BootstrapLauncher.main(BootstrapLauncher.java:141) [bootstraplauncher-1.1.2.jar:?] {}

A detailed walkthrough of the error, its code path and all known details is as follows:
---------------------------------------------------------------------------------------

-- Head --
Thread: Render thread
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
-- MOD panthalassa --
Details:
	Caused by 0: java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/SpawnPlacementRegisterEvent
		at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
		at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
		at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
		at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%2379!/:?] {}
		at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%2379!/:?] {}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.1.1.jar%23206!/:?] {}
		at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
		at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.1.1.jar%23206!/:?] {}
		at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.1.1.jar%23206!/:?] {}
		at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.1.jar%23205!/:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
		at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
		at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
		at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
		at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

	Mod File: /C:/Users/USER/Downloads/New folder (3)/Instances/1.19.2 survival/mods/panthalassa-1.3.2-1.19.2.jar
	Failure message: Panthalassa (panthalassa) has failed to load correctly
		java.lang.NoClassDefFoundError: net/minecraftforge/event/entity/SpawnPlacementRegisterEvent
	Mod Version: 1.3.2
	Mod Issue URL: https://github.com/Sniffity/Panthalassa/issues
	Exception message: java.lang.ClassNotFoundException: net.minecraftforge.event.entity.SpawnPlacementRegisterEvent
Stacktrace:
	at cpw.mods.cl.ModuleClassLoader.loadClass(ModuleClassLoader.java:141) ~[securejarhandler-2.1.4.jar:?] {}
	at java.lang.ClassLoader.loadClass(ClassLoader.java:520) ~[?:?] {}
	at java.lang.Class.getDeclaredMethods0(Native Method) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetDeclaredMethods(Class.java:3402) ~[?:?] {re:mixin}
	at java.lang.Class.privateGetPublicMethods(Class.java:3427) ~[?:?] {re:mixin}
	at java.lang.Class.getMethods(Class.java:2019) ~[?:?] {re:mixin}
	at net.minecraftforge.eventbus.EventBus.registerClass(EventBus.java:83) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.eventbus.EventBus.register(EventBus.java:126) ~[eventbus-6.0.3.jar%2379!/:?] {}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.lambda$inject$6(AutomaticEventSubscriber.java:61) ~[javafmllanguage-1.19.2-43.1.1.jar%23206!/:?] {}
	at java.util.ArrayList.forEach(ArrayList.java:1511) ~[?:?] {re:computing_frames,re:mixin}
	at net.minecraftforge.fml.javafmlmod.AutomaticEventSubscriber.inject(AutomaticEventSubscriber.java:48) ~[javafmllanguage-1.19.2-43.1.1.jar%23206!/:?] {}
	at net.minecraftforge.fml.javafmlmod.FMLModContainer.constructMod(FMLModContainer.java:78) ~[javafmllanguage-1.19.2-43.1.1.jar%23206!/:?] {}
	at net.minecraftforge.fml.ModContainer.lambda$buildTransitionHandler$10(ModContainer.java:121) ~[fmlcore-1.19.2-43.1.1.jar%23205!/:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1804) ~[?:?] {}
	at java.util.concurrent.CompletableFuture$AsyncRun.exec(CompletableFuture.java:1796) ~[?:?] {}
	at java.util.concurrent.ForkJoinTask.doExec(ForkJoinTask.java:373) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool$WorkQueue.topLevelExec(ForkJoinPool.java:1182) ~[?:?] {}
	at java.util.concurrent.ForkJoinPool.scan(ForkJoinPool.java:1655) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinPool.runWorker(ForkJoinPool.java:1622) ~[?:?] {re:computing_frames}
	at java.util.concurrent.ForkJoinWorkerThread.run(ForkJoinWorkerThread.java:165) ~[?:?] {}

-- System Details --
Details:
	Minecraft Version: 1.19.2
	Minecraft Version ID: 1.19.2
	Operating System: Windows 10 (amd64) version 10.0
	Java Version: 17.0.3, Microsoft
	Java VM Version: OpenJDK 64-Bit Server VM (mixed mode), Microsoft
	Memory: 429835992 bytes (409 MiB) / 1082130432 bytes (1032 MiB) up to 12884901888 bytes (12288 MiB)
	CPUs: 12
	Processor Vendor: GenuineIntel
	Processor Name: 11th Gen Intel(R) Core(TM) i5-11400F @ 2.60GHz
	Identifier: Intel64 Family 6 Model 167 Stepping 1
	Microarchitecture: unknown
	Frequency (GHz): 2.59
	Number of physical packages: 1
	Number of physical CPUs: 6
	Number of logical CPUs: 12
	Graphics card #0 name: NVIDIA GeForce GTX 1660
	Graphics card #0 vendor: NVIDIA (0x10de)
	Graphics card #0 VRAM (MB): 4095.00
	Graphics card #0 deviceId: 0x2184
	Graphics card #0 versionInfo: DriverVersion=31.0.15.1659
	Memory slot #0 capacity (MB): 8192.00
	Memory slot #0 clockSpeed (GHz): 2.67
	Memory slot #0 type: DDR4
	Memory slot #1 capacity (MB): 8192.00
	Memory slot #1 clockSpeed (GHz): 2.67
	Memory slot #1 type: DDR4
	Virtual memory max (MB): 29037.68
	Virtual memory used (MB): 13952.14
	Swap memory total (MB): 12800.00
	Swap memory used (MB): 307.47
	JVM Flags: 4 total; -XX:HeapDumpPath=MojangTricksIntelDriversForPerformance_javaw.exe_minecraft.exe.heapdump -Xss1M -Xmx12288m -Xms256m
	OptiFine Version: OptiFine_1.19.2_HD_U_I1_pre2
	OptiFine Build: 20220919-180220
	Render Distance Chunks: 8
	Mipmaps: 4
	Anisotropic Filtering: 1
	Antialiasing: 0
	Multitexture: false
	Shaders: null
	OpenGlVersion: 3.2.0 NVIDIA 516.59
	OpenGlRenderer: NVIDIA GeForce GTX 1660/PCIe/SSE2
	OpenGlVendor: NVIDIA Corporation
	CpuCount: 12
	ModLauncher: 10.0.8+10.0.8+main.0ef7e830
	ModLauncher launch target: forgeclient
	ModLauncher naming: srg
	ModLauncher services: 
		mixin-0.8.5.jar mixin PLUGINSERVICE 
		eventbus-6.0.3.jar eventbus PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar slf4jfixer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar object_holder_definalize PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar runtime_enum_extender PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar capability_token_subclass PLUGINSERVICE 
		accesstransformers-8.0.4.jar accesstransformer PLUGINSERVICE 
		fmlloader-1.19.2-43.1.1.jar runtimedistcleaner PLUGINSERVICE 
		modlauncher-10.0.8.jar mixin TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar OptiFine TRANSFORMATIONSERVICE 
		modlauncher-10.0.8.jar fml TRANSFORMATIONSERVICE 
	FML Language Providers: 
		minecraft@1.0
		lowcodefml@null
		javafml@null
	Mod List: 
		hexerei-0.2.5.jar                                 |Hexerei                       |hexerei                       |0.2.5               |COMMON_SET|Manifest: NOSIGNATURE
		incapacitated-1.19.2-1.3.jar                      |Incapacitated                 |incapacitated                 |1.19.2-1.3          |COMMON_SET|Manifest: NOSIGNATURE
		jei-1.19.2-forge-11.3.0.262.jar                   |Just Enough Items             |jei                           |11.3.0.262          |COMMON_SET|Manifest: NOSIGNATURE
		naturalist-forge-2.1.1-1.19.2.jar                 |Naturalist                    |naturalist                    |2.1.1               |COMMON_SET|Manifest: NOSIGNATURE
		libraryferret-forge-1.19.2-3.0.0.jar              |Library ferret                |libraryferret                 |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		Obscure+API+6+(Forge+1.19).jar                    |Obscure API                   |obscure_api                   |6                   |COMMON_SET|Manifest: NOSIGNATURE
		HorseExpert-v4.0.0-1.19.2-Forge.jar               |Horse Expert                  |horseexpert                   |4.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		Waystones-Mod-Forge-1.19.2.jar                    |Waystones                     |waystones                     |11.1.0              |COMMON_SET|Manifest: NOSIGNATURE
		awesomedungeon-forge-1.19.2-3.0.0.jar             |Awesome dungeon               |awesomedungeon                |3.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		TravelersBackpack-1.19.2-8.2.2.jar                |Traveler's Backpack           |travelersbackpack             |8.2.2               |COMMON_SET|Manifest: NOSIGNATURE
		badpackets-forge-0.2.0.jar                        |Bad Packets                   |badpackets                    |0.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		guardvillagers-1.19.2-1.5.2.jar                   |Guard Villagers               |guardvillagers                |1.19.2-1.5.2        |COMMON_SET|Manifest: NOSIGNATURE
		BlockySiege-3.2.2-1.19.2.jar                      |Blocky Siege                  |blocky_siege                  |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		u_team_core-1.19.2-4.3.1.231.jar                  |U Team Core                   |uteamcore                     |4.3.1.231           |COMMON_SET|Manifest: f4:a6:0b:ee:cb:8a:1a:ea:9f:9d:45:91:8f:8b:b3:ae:26:f3:bf:05:86:1d:90:9e:f6:32:2a:1a:ed:1d:ce:b0
		simpleplanes-1.19.2-5.0.3.jar                     |Simple Planes                 |simpleplanes                  |1.19.2-5.0.3        |COMMON_SET|Manifest: NOSIGNATURE
		redstructure-1.0.4-forge-1.19.2.jar               |Reds More Structures          |redmorestructure              |1.0.4-1.19.2        |COMMON_SET|Manifest: NOSIGNATURE
		balm-4.5.3.jar                                    |Balm                          |balm                          |4.5.3               |COMMON_SET|Manifest: NOSIGNATURE
		cloth-config-8.2.88-forge.jar                     |Cloth Config v8 API           |cloth_config                  |8.2.88              |COMMON_SET|Manifest: NOSIGNATURE
		forge-1.19.2-43.1.1-universal.jar                 |Forge                         |forge                         |43.1.1              |COMMON_SET|Manifest: 84:ce:76:e8:45:35:e4:0e:63:86:df:47:59:80:0f:67:6c:c1:5f:6e:5f:4d:b3:54:47:1a:9f:7f:ed:5e:f2:90
		supplementaries-1.19.2-2.2.16.jar                 |Supplementaries               |supplementaries               |1.19.2-2.2.16       |COMMON_SET|Manifest: NOSIGNATURE
		corpse-1.19.2-1.0.0.jar                           |Corpse                        |corpse                        |1.19.2-1.0.0        |COMMON_SET|Manifest: NOSIGNATURE
		client-1.19.2-20220805.130853-srg.jar             |Minecraft                     |minecraft                     |1.19.2              |COMMON_SET|Manifest: a1:d4:5e:04:4f:d3:d6:e0:7b:37:97:cf:77:b0:de:ad:4a:47:ce:8c:96:49:5f:0a:cf:8c:ae:b2:6d:4b:8a:3f
		FarmersDelight-1.19-1.2.0.jar                     |Farmer's Delight              |farmersdelight                |1.19-1.2.0          |COMMON_SET|Manifest: NOSIGNATURE
		panthalassa-1.3.2-1.19.2.jar                      |Panthalassa                   |panthalassa                   |1.3.2               |ERROR     |Manifest: NOSIGNATURE
		terravlender.jar                                  |TerraBlender                  |terrablender                  |2.0.1.127           |COMMON_SET|Manifest: NOSIGNATURE
		moonlight-1.19.2-2.1.6-forge.jar                  |Moonlight Library             |moonlight                     |1.19.2-2.1.6        |COMMON_SET|Manifest: NOSIGNATURE
		Aquamirae+4.3+API6+(Forge+1.19).jar               |Aquamirae                     |ob_aquamirae                  |4.3.6               |COMMON_SET|Manifest: NOSIGNATURE
		commonality-1.19.2-4.2.0.jar                      |Commonality                   |commonality                   |4.2.0               |COMMON_SET|Manifest: NOSIGNATURE
		BiomesOPlenty-1.19.2-17.1.1.150.jar               |Biomes O' Plenty              |biomesoplenty                 |17.1.1.150          |COMMON_SET|Manifest: NOSIGNATURE
		snowyspirit-1.19.2-2.0.9.jar                      |Snowy Spirit                  |snowyspirit                   |1.19.2-2.0.9        |COMMON_SET|Manifest: NOSIGNATURE
		vacuumchest-4.0.0-1.19.2.jar                      |Resistant Vacuum Chest        |resistantvacuumchest          |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		simplylight-1.19-1.4.4-build.39.jar               |Simply Light                  |simplylight                   |1.19-1.4.4-build.39 |COMMON_SET|Manifest: NOSIGNATURE
		wthit-forge-5.13.1.jar                            |wthit                         |wthit                         |5.13.1              |COMMON_SET|Manifest: NOSIGNATURE
		BarteringStation-v4.0.0-1.19.2-Forge.jar          |Bartering Station             |barteringstation              |4.0.0               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		curios-forge-1.19.2-5.1.1.0.jar                   |Curios API                    |curios                        |1.19.2-5.1.1.0      |COMMON_SET|Manifest: NOSIGNATURE
		Mekanism-1.19.1-10.3.1.468.jar                    |Mekanism                      |mekanism                      |10.3.1              |COMMON_SET|Manifest: NOSIGNATURE
		flywheel-forge-1.19.2-0.6.7-8.jar                 |Flywheel                      |flywheel                      |0.6.7-8             |COMMON_SET|Manifest: NOSIGNATURE
		create-1.19.2-0.5.0.f.jar                         |Create                        |create                        |0.5.0.f             |COMMON_SET|Manifest: NOSIGNATURE
		Patchouli-1.19.2-77.jar                           |Patchouli                     |patchouli                     |1.19.2-77           |COMMON_SET|Manifest: NOSIGNATURE
		fromspores-1.0.3.jar                              |From Spores                   |fromspores                    |1.0.3               |COMMON_SET|Manifest: NOSIGNATURE
		mod.jar                                           |Xaero's Minimap               |xaerominimap                  |22.15.1             |COMMON_SET|Manifest: NOSIGNATURE
		ShulkerTooltip-1.11.1.jar                         |Shulker Tooltip               |shulkertooltip                |1.11.1              |COMMON_SET|Manifest: NOSIGNATURE
		advancednetherite-1.13.7-1.19.2.jar               |Advanced Netherite            |advancednetherite             |1.13.7              |COMMON_SET|Manifest: NOSIGNATURE
		AutoRegLib-1.8-54.jar                             |AutoRegLib                    |autoreglib                    |1.8-54              |COMMON_SET|Manifest: NOSIGNATURE
		Quark-3.3-371.jar                                 |Quark                         |quark                         |3.3-371             |COMMON_SET|Manifest: NOSIGNATURE
		StorageDrawers-1.19-11.1.2.jar                    |Storage Drawers               |storagedrawers                |11.1.2              |COMMON_SET|Manifest: NOSIGNATURE
		bettervillage-forge-1.19.2-2.0.0.jar              |Better village                |bettervillage                 |2.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		InventoryHud_[1.19.2].forge-3.4.6.jar             |Inventory HUD+(Forge edition) |inventoryhud                  |3.4.6               |COMMON_SET|Manifest: NOSIGNATURE
		sprout-1.4.3-forge.jar                            |Sprout                        |sprout                        |1.4.3               |COMMON_SET|Manifest: NOSIGNATURE
		worldedit-mod-7.2.12.jar                          |WorldEdit                     |worldedit                     |7.2.12+6240-87f4ae1 |COMMON_SET|Manifest: NOSIGNATURE
		mvs-3.1.3.jar                                     |Moog's Voyager Structures     |mvs                           |3.1.3               |COMMON_SET|Manifest: NOSIGNATURE
		deeperdarker-1.0.0b-1.19.2.jar                    |Deeper And Darker             |deeperdarker                  |1.0.0b              |COMMON_SET|Manifest: NOSIGNATURE
		architectury-6.2.46-forge.jar                     |Architectury                  |architectury                  |6.2.46              |COMMON_SET|Manifest: NOSIGNATURE
		item-filters-forge-1902.2.9-build.41.jar          |Item Filters                  |itemfilters                   |1902.2.9-build.41   |COMMON_SET|Manifest: NOSIGNATURE
		apexcore-1.19.2-7.3.0.jar                         |ApexCore                      |apexcore                      |7.3.0               |COMMON_SET|Manifest: NOSIGNATURE
		fantasyfurniture-1.19.2-6.5.0.jar                 |Fantasy's Furniture           |fantasyfurniture              |6.5.0               |COMMON_SET|Manifest: NOSIGNATURE
		PuzzlesLib-v4.3.8-1.19.2-Forge.jar                |Puzzles Lib                   |puzzleslib                    |4.3.8               |COMMON_SET|Manifest: 9a:09:85:98:65:c4:8c:11:c5:49:f6:d6:33:23:39:df:8d:b4:ff:92:84:b8:bd:a5:83:9f:ac:7f:2a:d1:4b:6a
		BetterF3-4.0.0-Forge-1.19.2.jar                   |BetterF3                      |betterf3                      |4.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		layered_snowfall-1.0.0+-+1.18.2.jar               |Deeper Snow                   |layered_snowfall              |1.0.0               |COMMON_SET|Manifest: NOSIGNATURE
		geckolib-forge-1.19-3.1.36.jar                    |GeckoLib                      |geckolib3                     |3.1.36              |COMMON_SET|Manifest: NOSIGNATURE
	Crash Report UUID: e823b49e-b907-47e0-b152-2c9dcf0f9d41
	FML: 43.1
	Forge: net.minecraftforge:43.1.1
	Flywheel Backend: GL33 Instanced Arrays
![image](https://user-images.githubusercontent.com/89495658/201514041-cf26b631-ab55-4c37-a060-2ca0eae41bba.png)

**Comment by LagoOriginal** [comment]
Take off optifine

**Comment by Sniffity** [comment]
Updating Forge to the latest version for 1.19.2 (latest, not recommended should fix this issue. You are currently using Forge 43.1.1, latest should be 43.1.52 at the time of writing this.

For the poster above: As far as I am aware, this issue does not relate to OptiFine or mod corruption. While I understand you're trying to help, please allow me to handle GitHub issues, so as to avoid confusion.
